# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 00:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumegeneratormain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='year_start',
        ),
    ]
