# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 00:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('resumegeneratormain', '0002_remove_workexperience_year_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address',
            new_name='address_line_one',
        ),
        migrations.AddField(
            model_name='address',
            name='address_line_two',
            field=models.TextField(default=datetime.datetime(2016, 7, 23, 0, 16, 1, 416165, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
