# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 00:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumegeneratormain', '0003_auto_20160723_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_line_two',
        ),
    ]
