# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 00:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumegeneratormain', '0005_remove_address_address_line_one'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
