# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumegeneratormain', '0007_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='user',
        ),
        migrations.AddField(
            model_name='education',
            name='award_date',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='award_description',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.DeleteModel(
            name='Award',
        ),
    ]
