# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 00:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumegeneratormain', '0009_auto_20160723_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationaward',
            name='school',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='resumegeneratormain.Education'),
            preserve_default=False,
        ),
    ]
