# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 00:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumegeneratormain', '0010_educationaward_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationaward',
            name='school',
        ),
    ]
