# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumegeneratormain', '0011_remove_educationaward_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationaward',
            name='user',
        ),
        migrations.AddField(
            model_name='educationaward',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resumegeneratormain.Education'),
        ),
    ]
