# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumegeneratormain', '0012_auto_20160723_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='month_attained',
            field=models.DateField(verbose_name='%m'),
        ),
        migrations.AlterField(
            model_name='education',
            name='year_attained',
            field=models.DateField(verbose_name='%Y'),
        ),
        migrations.AlterField(
            model_name='education',
            name='year_finish',
            field=models.DateField(verbose_name='%Y'),
        ),
        migrations.AlterField(
            model_name='education',
            name='year_start',
            field=models.DateField(verbose_name='%Y'),
        ),
        migrations.AlterField(
            model_name='educationaward',
            name='award_date',
            field=models.DateField(blank=True, null=True, verbose_name='%Y'),
        ),
        migrations.AlterField(
            model_name='extracurricular',
            name='year_finish',
            field=models.DateField(verbose_name='%Y'),
        ),
        migrations.AlterField(
            model_name='extracurricular',
            name='year_start',
            field=models.DateField(verbose_name='%Y'),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='month',
            field=models.DateField(verbose_name='%m'),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='year',
            field=models.DateField(verbose_name='%Y'),
        ),
        migrations.AlterField(
            model_name='seminarattended',
            name='month',
            field=models.DateField(verbose_name='%m'),
        ),
        migrations.AlterField(
            model_name='seminarattended',
            name='year',
            field=models.DateField(verbose_name='%Y'),
        ),
        migrations.AlterField(
            model_name='seminarconducted',
            name='month',
            field=models.DateField(verbose_name='%m'),
        ),
        migrations.AlterField(
            model_name='seminarconducted',
            name='year',
            field=models.DateField(verbose_name='%Y'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='month_finish',
            field=models.DateField(verbose_name='%m'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='month_start',
            field=models.DateField(verbose_name='%m'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='year_finish',
            field=models.DateField(verbose_name='%Y'),
        ),
    ]
