# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumegeneratormain', '0013_auto_20160731_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='month_attained',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='education',
            name='year_attained',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='education',
            name='year_finish',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='education',
            name='year_start',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='educationaward',
            name='award_date',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='extracurricular',
            name='year_finish',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='extracurricular',
            name='year_start',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='month',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='seminarattended',
            name='month',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='seminarattended',
            name='year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='seminarconducted',
            name='month',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='seminarconducted',
            name='year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='month_finish',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='month_start',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='year_finish',
            field=models.CharField(max_length=4),
        ),
    ]
