# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 04:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resumegeneratormain', '0014_auto_20160801_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationaward',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
