# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-10 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumegenerator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('achieveid', models.AutoField(db_column='achieveID', primary_key=True, serialize=False)),
                ('userid', models.IntegerField(db_column='userID')),
                ('achievement', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Achievements',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressid', models.AutoField(db_column='addressID', primary_key=True, serialize=False)),
                ('userid', models.IntegerField(db_column='userID')),
                ('address', models.TextField()),
            ],
            options={
                'db_table': 'Address',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('awardid', models.AutoField(db_column='awardID', primary_key=True, serialize=False)),
                ('userid', models.IntegerField(db_column='userID')),
                ('award', models.TextField()),
                ('yearaward', models.CharField(db_column='yearAward', max_length=4)),
            ],
            options={
                'db_table': 'Award',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cellphone',
            fields=[
                ('cellphoneid', models.AutoField(db_column='cellphoneID', primary_key=True, serialize=False)),
                ('userid', models.IntegerField(db_column='userID')),
                ('cellnum', models.CharField(db_column='cellNum', max_length=20)),
            ],
            options={
                'db_table': 'Cellphone',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Curricular',
            fields=[
                ('curricularid', models.AutoField(db_column='curricularID', primary_key=True, serialize=False)),
                ('userid', models.IntegerField(db_column='userID')),
                ('yrstart', models.CharField(db_column='yrStart', max_length=4)),
                ('yrfin', models.CharField(db_column='yrFin', max_length=4)),
                ('position', models.CharField(max_length=45)),
                ('organization', models.CharField(max_length=45)),
                ('workdone', models.TextField(db_column='workDone')),
            ],
            options={
                'db_table': 'Curricular',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('educationid', models.AutoField(db_column='educationID', primary_key=True, serialize=False)),
                ('userid', models.IntegerField(db_column='userID')),
                ('yrstart', models.IntegerField(db_column='yrStart')),
                ('yrfin', models.IntegerField(db_column='yrFin')),
                ('school', models.CharField(max_length=45)),
                ('educattained', models.CharField(db_column='educAttained', max_length=45)),
                ('monthattained', models.CharField(db_column='monthAttained', max_length=45)),
                ('yearattained', models.CharField(db_column='yearAttained', max_length=45)),
            ],
            options={
                'db_table': 'Education',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('userid', models.IntegerField(db_column='userID', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'LogIn',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Researchpaper',
            fields=[
                ('researchpaperid', models.AutoField(db_column='researchPaperID', primary_key=True, serialize=False)),
                ('userid', models.IntegerField(db_column='userID')),
                ('month', models.CharField(max_length=45)),
                ('year', models.CharField(max_length=4)),
                ('title', models.CharField(max_length=70)),
                ('summary', models.TextField()),
            ],
            options={
                'db_table': 'ResearchPaper',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Seminarattend',
            fields=[
                ('seminarattendid', models.AutoField(db_column='seminarAttendID', primary_key=True, serialize=False)),
                ('userid', models.IntegerField(db_column='userID')),
                ('month', models.CharField(max_length=45)),
                ('year', models.CharField(max_length=4)),
                ('title', models.CharField(max_length=45)),
                ('seminarhead', models.CharField(db_column='seminarHead', max_length=45)),
                ('venue', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'SeminarAttend',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Seminarconduct',
            fields=[
                ('seminarconductid', models.AutoField(db_column='seminarConductID', primary_key=True, serialize=False)),
                ('userid', models.IntegerField(db_column='userID')),
                ('month', models.CharField(max_length=45)),
                ('year', models.CharField(max_length=4)),
                ('position', models.CharField(max_length=45)),
                ('title', models.CharField(max_length=45)),
                ('seminarhead', models.CharField(db_column='seminarHead', max_length=45)),
                ('venue', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'SeminarConduct',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('telephoneid', models.AutoField(db_column='telephoneID', primary_key=True, serialize=False)),
                ('userid', models.IntegerField(db_column='userID')),
                ('telnum', models.CharField(db_column='telNum', max_length=20)),
            ],
            options={
                'db_table': 'Telephone',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(db_column='userID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='firstName', max_length=45)),
                ('middleinitial', models.CharField(db_column='middleInitial', max_length=45)),
                ('lastname', models.CharField(db_column='lastName', max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('objective', models.TextField(blank=True, null=True)),
                ('background', models.TextField()),
            ],
            options={
                'db_table': 'User',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Workexp',
            fields=[
                ('workexpid', models.AutoField(db_column='workExpID', primary_key=True, serialize=False)),
                ('userid', models.IntegerField(db_column='userID')),
                ('monthstart', models.CharField(db_column='monthStart', max_length=45)),
                ('yearstart', models.CharField(db_column='yearStart', max_length=4)),
                ('monthfin', models.CharField(db_column='monthFin', max_length=45)),
                ('yearfin', models.CharField(db_column='yearFin', max_length=4)),
                ('position', models.CharField(max_length=45)),
                ('company', models.CharField(max_length=45)),
                ('workdone', models.TextField(db_column='workDone')),
            ],
            options={
                'db_table': 'WorkExp',
                'managed': True,
            },
        ),
    ]
